export const keys = {
  Backquote: {
    en: '`',
    ru: 'ё',
    shiftEn: '~',
    shiftRu: 'Ё',
    capsEn: '`',
    capsRu: 'Ё',
  },
  Digit1: {
    en: '1',
    ru: '1',
    shiftEn: '!',
    shiftRu: '!',
    capsEn: '1',
    capsRu: '1',
  },
  Digit2: {
    en: '2',
    ru: '2',
    shiftEn: '@',
    shiftRu: '"',
    capsEn: '2',
    capsRu: '2',
  },
  Digit3: {
    en: '3',
    ru: '3',
    shiftEn: '#',
    shiftRu: '№',
    capsEn: '3',
    capsRu: '3',
  },
  Digit4: {
    en: '4',
    ru: '4',
    shiftEn: '$',
    shiftRu: ';',
    capsEn: '4',
    capsRu: '4',
  },
  Digit5: {
    en: '5',
    ru: '5',
    shiftEn: '%',
    shiftRu: '%',
    capsEn: '5',
    capsRu: '5',
  },
  Digit6: {
    en: '6',
    ru: '6',
    shiftEn: '^',
    shiftRu: ':',
    capsEn: '6',
    capsRu: '6',
  },
  Digit7: {
    en: '7',
    ru: '7',
    shiftEn: '&',
    shiftRu: '?',
    capsEn: '7',
    capsRu: '7',
  },
  Digit8: {
    en: '8',
    ru: '8',
    shiftEn: '*',
    shiftRu: '*',
    capsEn: '8',
    capsRu: '8',
  },
  Digit9: {
    en: '9',
    ru: '9',
    shiftEn: '(',
    shiftRu: '(',
    capsEn: '9',
    capsRu: '9',
  },
  Digit0: {
    en: '0',
    ru: '0',
    shiftEn: ')',
    shiftRu: ')',
    capsEn: '0',
    capsRu: '0',
  },
  Minus: {
    en: '-',
    ru: '-',
    shiftEn: '_',
    shiftRu: '_',
    capsEn: '-',
    capsRu: '-',
  },
  Equal: {
    en: '=',
    ru: '=',
    shiftEn: '+',
    shiftRu: '+',
    capsEn: '=',
    capsRu: '=',
  },
  Backspace: {
    en: 'Backspace',
    ru: 'Backspace',
    shiftEn: 'Backspace',
    shiftRu: 'Backspace',
    capsEn: 'Backspace',
    capsRu: 'Backspace',
  },
  Tab: {
    en: 'Tab',
    ru: 'Tab',
    shiftEn: 'Tab',
    shiftRu: 'Tab',
    capsEn: 'Tab',
    capsRu: 'Tab',
  },
  KeyQ: {
    en: 'q',
    ru: 'й',
    shiftEn: 'Q',
    shiftRu: 'Й',
    capsEn: 'Q',
    capsRu: 'Й',
  },
  KeyW: {
    en: 'w',
    ru: 'ц',
    shiftEn: 'W',
    shiftRu: 'Ц',
    capsEn: 'W',
    capsRu: 'Ц',
  },
  KeyE: {
    en: 'e',
    ru: 'у',
    shiftEn: 'E',
    shiftRu: 'У',
    capsEn: 'E',
    capsRu: 'У',
  },
  KeyR: {
    en: 'r',
    ru: 'к',
    shiftEn: 'R',
    shiftRu: 'К',
    capsEn: 'R',
    capsRu: 'К',
  },
  KeyT: {
    en: 't',
    ru: 'е',
    shiftEn: 'T',
    shiftRu: 'Е',
    capsEn: 'T',
    capsRu: 'Е',
  },
  KeyY: {
    en: 'y',
    ru: 'н',
    shiftEn: 'Y',
    shiftRu: 'Н',
    capsEn: 'Y',
    capsRu: 'Н',
  },
  KeyU: {
    en: 'u',
    ru: 'г',
    shiftEn: 'U',
    shiftRu: 'Г',
    capsEn: 'U',
    capsRu: 'Г',
  },
  KeyI: {
    en: 'i',
    ru: 'ш',
    shiftEn: 'I',
    shiftRu: 'Ш',
    capsEn: 'I',
    capsRu: 'Ш',
  },
  KeyO: {
    en: 'o',
    ru: 'щ',
    shiftEn: 'O',
    shiftRu: 'Щ',
    capsEn: 'O',
    capsRu: 'Щ',
  },
  KeyP: {
    en: 'p',
    ru: 'з',
    shiftEn: 'P',
    shiftRu: 'З',
    capsEn: 'P',
    capsRu: 'З',
  },
  BracketLeft: {
    en: '[',
    ru: 'х',
    shiftEn: '{',
    shiftRu: 'Х',
    capsEn: '[',
    capsRu: 'Х',
  },
  BracketRight: {
    en: ']',
    ru: 'ъ',
    shiftEn: '}',
    shiftRu: 'Ъ',
    capsEn: ']',
    capsRu: 'Ъ',
  },
  Backslash: {
    en: '\\',
    ru: '\\',
    shiftEn: '|',
    shiftRu: '/',
    capsEn: '\\',
    capsRu: '\\',
  },
  CapsLock: {
    en: 'CapsLock',
    ru: 'CapsLock',
    shiftEn: 'CapsLock',
    shiftRu: 'CapsLock',
    capsEn: 'CapsLock',
    capsRu: 'CapsLock',
  },
  KeyA: {
    en: 'a',
    ru: 'ф',
    shiftEn: 'A',
    shiftRu: 'Ф',
    capsEn: 'A',
    capsRu: 'Ф',
  },
  KeyS: {
    en: 's',
    ru: 'ы',
    shiftEn: 'S',
    shiftRu: 'Ы',
    capsEn: 'S',
    capsRu: 'Ы',
  },
  KeyD: {
    en: 'd',
    ru: 'в',
    shiftEn: 'D',
    shiftRu: 'В',
    capsEn: 'D',
    capsRu: 'В',
  },
  KeyF: {
    en: 'f',
    ru: 'а',
    shiftEn: 'F',
    shiftRu: 'А',
    capsEn: 'F',
    capsRu: 'А',
  },
  KeyG: {
    en: 'g',
    ru: 'п',
    shiftEn: 'G',
    shiftRu: 'П',
    capsEn: 'G',
    capsRu: 'П',
  },
  KeyH: {
    en: 'h',
    ru: 'р',
    shiftEn: 'H',
    shiftRu: 'Р',
    capsEn: 'H',
    capsRu: 'Р',
  },
  KeyJ: {
    en: 'j',
    ru: 'о',
    shiftEn: 'J',
    shiftRu: 'О',
    capsEn: 'J',
    capsRu: 'О',
  },
  KeyK: {
    en: 'k',
    ru: 'л',
    shiftEn: 'K',
    shiftRu: 'Л',
    capsEn: 'K',
    capsRu: 'Л',
  },
  KeyL: {
    en: 'l',
    ru: 'д',
    shiftEn: 'L',
    shiftRu: 'Д',
    capsEn: 'L',
    capsRu: 'Д',
  },
  Semicolon: {
    en: ';',
    ru: 'ж',
    shiftEn: ':',
    shiftRu: 'Ж',
    capsEn: ';',
    capsRu: 'Ж',
  },
  Quote: {
    en: '\'',
    ru: 'э',
    shiftEn: '"',
    shiftRu: 'Э',
    capsEn: '\'',
    capsRu: 'Э',
  },
  Enter: {
    en: 'Enter',
    ru: 'Enter',
    shiftEn: 'Enter',
    shiftRu: 'Enter',
    capsEn: 'Enter',
    capsRu: 'Enter',
  },
  ShiftLeft: {
    en: 'Shift',
    ru: 'Shift',
    shiftEn: 'Shift',
    shiftRu: 'Shift',
    capsEn: 'Shift',
    capsRu: 'Shift',
  },
  KeyZ: {
    en: 'z',
    ru: 'я',
    shiftEn: 'Z',
    shiftRu: 'Я',
    capsEn: 'Z',
    capsRu: 'Я',
  },
  KeyX: {
    en: 'x',
    ru: 'ч',
    shiftEn: 'X',
    shiftRu: 'Ч',
    capsEn: 'X',
    capsRu: 'Ч',
  },
  KeyC: {
    en: 'c',
    ru: 'с',
    shiftEn: 'C',
    shiftRu: 'С',
    capsEn: 'C',
    capsRu: 'С',
  },
  KeyV: {
    en: 'v',
    ru: 'м',
    shiftEn: 'V',
    shiftRu: 'М',
    capsEn: 'V',
    capsRu: 'М',
  },
  KeyB: {
    en: 'b',
    ru: 'и',
    shiftEn: 'B',
    shiftRu: 'И',
    capsEn: 'B',
    capsRu: 'И',
  },
  KeyN: {
    en: 'n',
    ru: 'т',
    shiftEn: 'N',
    shiftRu: 'Т',
    capsEn: 'N',
    capsRu: 'Т',
  },
  KeyM: {
    en: 'm',
    ru: 'ь',
    shiftEn: 'M',
    shiftRu: 'Ь',
    capsEn: 'M',
    capsRu: 'Ь',
  },
  Comma: {
    en: ',',
    ru: 'б',
    shiftEn: '<',
    shiftRu: 'Б',
    capsEn: ',',
    capsRu: 'Б',
  },
  Period: {
    en: '.',
    ru: 'ю',
    shiftEn: '>',
    shiftRu: 'Ю',
    capsEn: '.',
    capsRu: 'Ю',
  },
  Slash: {
    en: '/',
    ru: '.',
    shiftEn: '?',
    shiftRu: ',',
    capsEn: '/',
    capsRu: '.',
  },
  ArrowUp: {
    en: '&#8593;',
    ru: '&#8593;',
    shiftEn: '&#8593;',
    shiftRu: '&#8593;',
    capsEn: '&#8593;',
    capsRu: '&#8593;',
  },
  ShiftRight: {
    en: 'Shift',
    ru: 'Shift',
    shiftEn: 'Shift',
    shiftRu: 'Shift',
    capsEn: 'Shift',
    capsRu: 'Shift',
  },
  ControlLeft: {
    en: 'Ctrl',
    ru: 'Ctrl',
    shiftEn: 'Ctrl',
    shiftRu: 'Ctrl',
    capsEn: 'Ctrl',
    capsRu: 'Ctrl',
  },
  AltLeft: {
    en: 'Alt',
    ru: 'Alt',
    shiftEn: 'Alt',
    shiftRu: 'Alt',
    capsEn: 'Alt',
    capsRu: 'Alt',
  },
  Space: {
    en: 'Space',
    ru: 'Space',
    shiftEn: 'Space',
    shiftRu: 'Space',
    capsEn: 'Space',
    capsRu: 'Space',
  },
  AltRight: {
    en: 'Alt',
    ru: 'Alt',
    shiftEn: 'Alt',
    shiftRu: 'Alt',
    capsEn: 'Alt',
    capsRu: 'Alt',
  },
  ArrowLeft: {
    en: '&#8592;',
    ru: '&#8592;',
    shiftEn: '&#8592;',
    shiftRu: '&#8592;',
    capsEn: '&#8592;',
    capsRu: '&#8592;',
  },
  ArrowDown: {
    en: '&#8595;',
    ru: '&#8595;',
    shiftEn: '&#8595;',
    shiftRu: '&#8595;',
    capsEn: '&#8595;',
    capsRu: '&#8595;',
  },
  ArrowRight: {
    en: '&#8594;',
    ru: '&#8594;',
    shiftEn: '&#8594;',
    shiftRu: '&#8594;',
    capsEn: '&#8594;',
    capsRu: '&#8594;',
  },
  ControlRight: {
    en: 'Ctrl',
    ru: 'Ctrl',
    shiftEn: 'Ctrl',
    shiftRu: 'Ctrl',
    capsEn: 'Ctrl',
    capsRu: 'Ctrl',
  },
};
